id: msp.fhir.do
canonical: https://digital.msp.gob.do/fhir/conectaton
name: fhir-ig-do
title: "Guía FHIR DO - Conectaton Nacional República Dominicana"
description: "Guía Conectaton Nacional de República Dominicana para recursos, extensiones, terminologías y patrones comunes de interoperabilidad FHIR."
language: es
license: CC-BY-4.0
status: draft
version: 0.2.0
fhirVersion: 4.0.1
copyrightYear: 2026
releaseLabel: "ci-build"
jurisdiction: urn:iso:std:iso:3166#DO "Dominican Republic"
publisher:
  name: "Ministerio de Salud Pública y Asistencia Social"
  url: "https://msp.gob.do"

dependencies:
  hl7.fhir.uv.ips: 2.0.0-ballot
  ihe.iti.mhd: 4.2.2

parameters:
  show-inherited-invariants: false
  apply-contact: true
  excludettl: true
  excludexml: true
  excludemap: true

menu:
  Inicio: index.html
  BASE:
    Paciente: StructureDefinition-PatientDO.html
    Profesional: StructureDefinition-PractitionerDO.html
    Organización: StructureDefinition-OrganizationDO.html
  INFORMACION CLINICA:
    Alergias: StructureDefinition-AllergyIntoleranceDO.html
    Medicamentos: StructureDefinition-MedicationStatementDO.html
    Condition: StructureDefinition-ConditionDO.html
  DOCUMENTOS:   
    1-Resumen Paciente: resumenpaciente.html
    2-Notificación Individual Caso: notificacionepidemiologica.html
    3-Registro Nacional de Cáncer: resumenoncologico.html
  MHD: 
    List: StructureDefinition-ListDO.html
    IndiceDocumentos: StructureDefinition-DocumentReferenceDO.html
    Transaccion: StructureDefinition-BundleTransaccDO.html
  TERMINOLOGIAS:
    Terminologia: terminologias.html
  CONECTATON 2026:
    Detalles: conectaton.html
    Validación: validacion.html
  OTROS:
    Descargas: descargas.html
